<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>

    <style>
        body {
            font-family: system-ui;
        }
    </style>
</head>


<body>
    <h1>Async/Await in JavaScript : Just one more way of handling a promise </h1>
    nice way of handling promises
    <b>
        In some cases where we will .then .then .then .... for a promise in this cases we will be using Async and Await

        <caption>
            There is a special syntax to work with promise in JavaScript
        </caption>

        <pre>

<hr>
<marquee behavior="" direction=""><h2 style="color: red;">Important</h2></marquee>
<h1>1 Simple Eg to understand Async / Await</h1>

// Simple Eg to understand Async / Await


// let simplePromise = new Promise((resolve, reject) => {
//     setTimeout(() => {
//         console.log("Simple promise in 3 secs")
//         resolve('resolving  simplePromise')
//         // or  do any thing is fine
//         // reject('Rejecting the simplePromise')
//     }, 3000)
// })


// 1 One way of handling promise is using .then and .catch methods 


// simplePromise.then((response) => {
//     console.log(response)
//     alert("simple alert is resolved")
// }).catch((error) => {
//     console.log(error)
//     alert("simple alert is  not resolved")
// })


//2 using Async and await ,
//Two rules ,call the promise inside a async function , and assign await to the promise 
// so that the resolved / rejected data is there taken in variable

//1
// async function handlePromise() {


//     //2  take the promise add await and assign to the variable 

//     //Handling error by try catch block
//     try {
//         console.log('handling promise')
//         let promise = await simplePromise //since this is a promise no need of addlike this simplePromise() as this is not a function
//         console.log(promise)

//         //now commenting out resolve and commenting reject()
//     }
//     catch (error) {
//         console.log(error + " error is handled")
//     }
// }


// handlePromise()

<br>
<h1>2 Simple Eg2 to understand Async / Await</h1>

// 2 other way of understating async/ await

// function demoPromise() {
//     return new Promise((resolve, reject) => {
//         console.log('starting promise')
//         setTimeout(() => {
//             console.log('Promise resolved after 2 secs')
//             resolve('Resolving Promise')
//             // or
//             // reject('Rejecting Promise ')
//         }, 2000)
//     })
// }


//1 handling successful scenario and failure scenario
// demoPromise().then((resolve) => {
//     console.log(resolve)
// }, (error) => { console.log(error) })

//2 handling successful scenario and failure scenario

// async function doSomethingTask() {
//     try {
//         let response = await demoPromise() // since demopromise is a function so we are calling like a function
//         console.log(response)
//     }
//     catch (error) {
//         console.log(error)
//     }
// }

// doSomethingTask()
<hr>

            <h2>
Any function can be made Async with the keyword async like this , 

async function doSomething()
{
    //////
    return 7;
}

The Await keyword

There is another keyword called await , that works only inside async functions 
let value = await promise , so here until the promise is resolved /rejected it will wait and return the value and we can call .then() to the function as the function is a async function
The await keyword makes JavaScript wait until the promise settles and return its value 

Note:
<u>A Async function always returns a Promise</u>

Since doSomething is returning a Function now we can also use then() and catch()

doSomething().then(alert) and Since doSomething is returning a value i.e 7 we can get it from .then()


so Async ensures that the function returns a promise and wraps non promises automatically
</h2>
<hr>
<h1> // Exercise 1 login and validate With Promise</h1>


// const userLogin = () => {
//     console.log('Enter Username and Password')
//     let username = prompt("Enter the Username")
//     let password = prompt("Enter the Password")

//     return new Promise((resolve, reject) => {

//         setTimeout(() => {
//             console.log("Performing User Authentication")
//             if (username === 'ashu' && password == 'dummy') {
//                 resolve('User Authenticated')
//             } else {
//                 reject('Authentication Failed')
//             }
//         }, 2000)
//     })
// }


// function goToHomePage(UserAuthStatus) {
//     return Promise.resolve(`Go to Homepage as : ${UserAuthStatus}`)
// }


// userLogin().then((response) => {
//     console.log(response + " Validated User")
//     let responsedata = goToHomePage(response)//this returns a Promise so we can call .then() i.e we can do promise chaining but we have to return it 

//     return responsedata;
// }).then((response) => {

//     console.log(response)

// }, (error) => { console.log(error + " Error while Authenticating") })

<hr>

<h1>//The same logic can be written in more concise/readable way by async/wait function
    //Async and Await function </h1>



const userLogin = () => {
    console.log('Enter Username and Password')
    let username = prompt("Enter the Username")
    let password = prompt("Enter the Password")

    return new Promise((resolve, reject) => {

        setTimeout(() => {
            console.log("Performing User Authentication")
            if (username === 'ashu' && password == 'dummy') {
                resolve('User Authenticated')
            } else {
                reject('Authentication Failed')
            }
        }, 2000)
    })
}


function goToHomePage(UserAuthStatus) {
    return Promise.resolve(`Go to Homepage as : ${UserAuthStatus}`)
}

async function performTask() {

    const response = await userLogin();//wait till resolve or rejects and gives the response
    console.log('User Validated')
    const UserAuthStatus = await goToHomePage(response)
    console.log(UserAuthStatus)


}

performTask()

//same o/p as above
 
<hr>

        </pre>
    </b>
    <script>


        // 2 other way of understating async/ await

        // function demoPromise() {
        //     return new Promise((resolve, reject) => {
        //         console.log('starting promise')
        //         setTimeout(() => {
        //             console.log('Promise resolved after 2 secs')
        //             resolve('Resolving Promise')
        //             // or
        //             // reject('Rejecting Promise ')
        //         }, 2000)
        //     })
        // }


        //1 handling successful scenario and failure scenario
        // demoPromise().then((resolve) => {
        //     console.log(resolve)
        // }, (error) => { console.log(error) })

        //2 handling successful scenario and failure scenario

        // async function doSomethingTask() {
        //     try {
        //         let response = await demoPromise() // since demopromise is a function so we are calling like a function
        //         console.log(response)
        //     }
        //     catch (error) {
        //         console.log(error)
        //     }
        // }

        // doSomethingTask()











        // Simple Eg to understand Async / Await


        // let simplePromise = new Promise((resolve, reject) => {
        //     setTimeout(() => {
        //         console.log("Simple promise in 3 secs")
        //         resolve('resolving  simplePromise')
        //         // or  do any thing is fine
        //         // reject('Rejecting the simplePromise')
        //     }, 3000)
        // })


        // 1 One way of handling promise is using .then and .catch methods


        // simplePromise.then((response) => {
        //     console.log(response)
        //     alert("simple alert is resolved")
        // }).catch((error) => {
        //     console.log(error)
        //     alert("simple alert is  not resolved")
        // })


        //2 using Async and await ,
        //Two rules ,call the promise inside a async function , and assign await to the promise
        // so that the resolved / rejected data is there taken in variable

        //1
        // async function handlePromise() {


        //     //2  take the promise add await and assign to the variable

        //     //Handling error by try catch block
        //     try {
        //         console.log('handling promise')
        //         let promise = await simplePromise //since this is a promise no need of addlike this simplePromise() as this is not a function
        //         console.log(promise)

        //         //now commenting out resolve and commenting reject()
        //     }
        //     catch (error) {
        //         console.log(error + " error is handled")
        //     }
        // }


        // handlePromise()

        //Testing async
        // async function doSomething() {

        //     return "SomeData"
        // }




        //Removing async and calling .then for doSomething()
        // function doSomething() {

        //     return "SomeData"
        // }
        //error in console
        // if for a function if there is no async and if we call then to it we will get
        // Async - Await -in -JavaScript.html: 63 Uncaught TypeError: doSomething(...).then is not a function
        //     at http://127.0.0.1:5500/Practise/C9(Callbacks-Promises-Async&Await-TryCatchFinally)/Async-Await-in-JavaScript.html:63:23


        // doSomething().then((data) => {
        //     alert(data)
        // })
        // //  or
        // doSomething().then(
        //     alert('data')
        // )

        // Exercise 1 login and validate With Promise

        // const userLogin = () => {
        //     console.log('Enter Username and Password')
        //     let username = prompt("Enter the Username")
        //     let password = prompt("Enter the Password")

        //     return new Promise((resolve, reject) => {

        //         setTimeout(() => {
        //             console.log("Performing User Authentication")
        //             if (username === 'ashu' && password == 'dummy') {
        //                 resolve('User Authenticated')
        //             } else {
        //                 reject('Authentication Failed')
        //             }
        //         }, 2000)
        //     })
        // }


        // function goToHomePage(UserAuthStatus) {
        //     return Promise.resolve(`Go to Homepage as : ${UserAuthStatus}`)
        // }


        // userLogin().then((response) => {
        //     console.log(response + " Validated User")
        //     let responsedata = goToHomePage(response)//this returns a Promise so we can call .then() i.e we can do promise chaining but we have to return it

        //     return responsedata;
        // }).then((response) => {

        //     console.log(response)

        // }, (error) => { console.log(error + " Error while Authenticating") })



        //The same logic can be written in more concise/readable way by async/wait function
        //Async and Await function

        // const userLogin = () => {
        //     console.log('Enter Username and Password')
        //     let username = prompt("Enter the Username")
        //     let password = prompt("Enter the Password")

        //     return new Promise((resolve, reject) => {

        //         setTimeout(() => {
        //             console.log("Performing User Authentication")
        //             if (username === 'ashu' && password == 'dummy') {
        //                 resolve('User Authenticated')
        //             } else {
        //                 reject('Authentication Failed')
        //             }
        //         }, 2000)
        //     })
        // }


        // function goToHomePage(UserAuthStatus) {
        //     return Promise.resolve(`Go to Homepage as : ${UserAuthStatus}`)
        // }
        // // here we are not able to handle un-successfull scenario by .catch() but we will use try catch block

        // async function performTask() {

        //     try {
        //         const response = await userLogin();//wait till resolve or rejects and gives the response
        //         console.log('User Validated')
        //         const UserAuthStatus = await goToHomePage(response)
        //         console.log(UserAuthStatus)
        //     }
        //     catch (error) {

        //         console.log(error)
        //     }

        // }

        // performTask()

        //same o/p as above




        //Exercise Network call
        async function fetchRandomData(id) {

            try {
                let data = await fetch(`https://jsonplaceholder.typicode.com/todos/${id}`)
                let jsonData = await data.json();
                console.log(JSON.stringify(jsonData) + " is the data")
            }
            catch (error) {
                console.warn(error + " error while calling the api , userID " + id)
            }
        }


        fetchRandomData(2)

    </script>
</body>

</html>